---
title: "Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(tidyverse)
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# Number of items ordered in each department
```{r}
instacart |> 
  count(department) |> 
  mutate(department = fct_reorder(department, n)) |> 
  plot_ly(
    x = ~department, y = ~n, type = "scatter", mode = "markers",
    color = ~department,  alpha = 0.5)
```
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart |> 
  count(department) |> 
  mutate(department = fct_reorder(department, n)) |> 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```

### Chart C

```{r}
instacart|>
  mutate(department = fct_reorder(department, order_number)) |> 
  plot_ly(y = ~order_number, color = ~department, type = "box", colors = "viridis")
```

